export const background_colors = {
    "world news": "#FF5E5B",
    "health": "#FEC8FF",
    "science": "#D2FFD2",
    "technology": "#67B3EE",
    "politics": "#F9C784",
    "sports": "#FF9A5B",
    "environment": "#6EEB83",
    "tech": "#67B3EE",
    "entertainment": "#E0A9FB",
    "business": "#D1F5FF",
    "crime": "#C672BF",
    "transportation": "#FFD2D2",
    "human rights": "#FF5E5B",
    "gun control": "#9D847F",
    "us politics": "#F9C784",
    "social issues": "#FFD2FF",
    "cryptocurrency": "#D1F5FF",
    "economy": "#D2FFD2",
    "automotive": "#FF9A5B",
    "disaster": "#FF5E5B",
    "legal": "#F9C784",
    "finance": "#D1F5FF",
    "business & finance": "#D1F5FF",
    "education & technology": "#67B3EE",
    "health & science": "#D2FFD2",
    "politics & economy": "#F9C784",
    "privacy & security": "#C672BF",
    "society": "#FFD2FF",
    "conflict": "#FF5E5B",
    "media": "#FFD2FF",
    "news": "#D1F5FF",
    "diplomacy": "#D2FFD2",
    "gaming": "#C07FF6",
    "art & entertainment": "#FFD2FF",
    "social media": "#F16286",
    "movies": "#C07FF6",
    "world": "#FF5E5B",
    "accidents & disasters": "#FF5E5B",
    "military": "#9D847F",
    "climate": "#6EEB83",
    "artificial intelligence": "#67B3EE",
    "gender": "#FEC8FF",
    "law": "#F9C784",
    "lifestyle": "#FFD2FF",
    "religion": "#C672BF",
    "arts": "#E0A9FB",
    "ai": "#67B3EE",
    "human interest": "#FF5E5B",
    "space": "#b669f5",
    "archeology": "#9D847F",
    "environmental issues": "#6EEB83",
    "travel": "#FFD2FF",
    "education": "#69E073",
    "auto": "#FF9A5B",
    "automobiles": "#FF9A5B",
    "culture": "#E0A9FB",
    "video games": "#C07FF6",
}