export const background_colors = {
    "": "#67B3EE",
    "all": "#FF5E5B",
    "world news": "#FF5E5B",
    "health": "#FEC8FF",
    "science": "#D2FFD2",
    "technology": "#67B3EE",
    "politics": "#F9C784",
    "sports": "#FF9A5B",
    "environment": "#6EEB83",
    "tech": "#67B3EE",
    "entertainment": "#E0A9FB",
    "business": "#D1F5FF",
    "crime": "#C672BF",
    "transportation": "#FFD2D2",
    "human rights": "#FF5E5B",
    "gun control": "#9D847F",
    "us politics": "#F9C784",
    "social issues": "#FFD2FF",
    "cryptocurrency": "#D1F5FF",
    "economy": "#D2FFD2",
    "automotive": "#FF9A5B",
    "disaster": "#FF5E5B",
    "legal": "#F9C784",
    "finance": "#D1F5FF",
    "business & finance": "#D1F5FF",
    "education & technology": "#67B3EE",
    "health & science": "#D2FFD2",
    "politics & economy": "#F9C784",
    "privacy & security": "#C672BF",
    "society": "#FFD2FF",
    "conflict": "#FF5E5B",
    "media": "#FFD2FF",
    "news": "#D1F5FF",
    "diplomacy": "#D2FFD2",
    "gaming": "#C07FF6",
    "art & entertainment": "#FFD2FF",
    "social media": "#F16286",
    "movies": "#C07FF6",
    "world": "#FF5E5B",
    "accidents & disasters": "#FF5E5B",
    "military": "#9D847F",
    "climate": "#6EEB83",
    "artificial intelligence": "#67B3EE",
    "gender": "#FEC8FF",
    "law": "#F9C784",
    "lifestyle": "#FFD2FF",
    "religion": "#C672BF",
    "arts": "#E0A9FB",
    "ai": "#67B3EE",
    "human interest": "#FF5E5B",
    "space": "#b669f5",
    "archeology": "#9D847F",
    "environmental issues": "#6EEB83",
    "travel": "#FFD2FF",
    "education": "#69E073",
    "auto": "#FF9A5B",
    "automobiles": "#FF9A5B",
    "automobile": "#FF9A5B",
    "culture": "#E0A9FB",
    "video games": "#C07FF6",
    "sci-tech": "#C2F3D6",
    "music": "#E0A9FB",
    "shopping": "#FFD2FF",
    "weather": "#6EEB83",
    "global news": "#FF5E5B",
    "arts and entertainment": "#C07FF6",
    "air quality": "#6EEB83",
    "history": "#9D847F",
    "jobs": "#F9C784",
    "legal affairs": "#F9C784",
    "robotic technology": "#67B3EE",
    "tech news": "#67B3EE",
    "astronomy": "#b669f5",
    "oceanography": "#3d9feb",
    "archaeology": "#9D847F",
    "cars": "#FF9A5B",
    "career": "#E0A9FB",
    "africa": "#FF5E5B",
    "bitcoin": "#D1F5FF",
    "electric cars": "#67B3EE",
    "europe": "#FF5E5B",
    "home appliances": "#FFD2FF",
    "security": "#C672BF",
    "social networking": "#F16286",
    "cybersecurity": "#C672BF",
    "business/streaming": "#D1F5FF",
    "entertainment/gaming": "#C07FF6",
    "lifestyle/shopping": "#FFD2FF",
    "technology/cybersecurity": "#C672BF",
    "technology/social media": "#F16286",
    "world/africa": "#FF5E5B",
    "world/europe": "#FF5E5B",
    "world/politics": "#F9C784",
    "world/religion": "#C672BF",
    "world/science": "#D2FFD2",
    "home and kitchen": "#FFD2FF",
    "energy": "#6EEB83",
    "streaming": "#C07FF6",
    "esports": "#b669f5",
    "cycling": "#ffe45b",
    "justice/law": "#EDB392",
    "sales/deals": "#FFD2FF",
    "events/conferences": "#FFD2FF",
}